language: python
python:
  - 2.7
  - 3.6

services:
  - docker

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy scikit-learn nose sqlalchemy thrift
  - source activate test-environment

install:
  - pip install pandas-td pyhive thrift-sasl # other deps not in conda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      # python-dateutil<2.5.0,>=2.4.0 is required by td-client-python
      pip install python-dateutil==2.4.0;
    fi
  - python setup.py install

before_script:
  - cd docker
  - docker-compose up -d
  - cd ..
  - sleep 60 # wait for a while until HiveServer2 is successfully launched.

script:
  - nosetests . -v

notifications:
  email: false
